### PR TITLE
Add permissions

### PR DESCRIPTION
**Pull request by Woodie-07**
- Add permissions so that normal players cannot reset the hearts.

### CODE REVIEW

**Comment by Founntain** [comment]
Thank you for your contribution, but just to make sure. The java code doesn't have to be updated or what? Like check for the permissions etc. inside the CommandExecutor?

Sorry for my late reply.

**Comment by Woodie-07** [comment]
> Thank you for your contribution, but just to make sure. The java code doesn't have to be updated or what? Like check for the permissions etc. inside the CommandExecutor?
> 
> 
> 
> Sorry for my late reply.

Yes, only the plugin.yml has to be modified. Nothing else has to be changed. You can test it if you want to make sure but it worked just fine for me.

**Comment by Founntain** [comment]
> Yes, only the plugin.yml has to be modified. Nothing else has to be changed. You can test it if you want to make sure but it worked just fine for me.

Ok, thanks for clarifying, I'm not that much into permissions. Will test it tommorow and if all works fine I'll merge it.

**Comment by Founntain** [comment]
Works fine, merged

**Pull request merged**
